### ISSUE TITLE
The Anniversary Update TODO

### ISSUE THREAD

**Issue by dreamscached** [Friends-of-Monika/mas-selfharm#3]
*Maybe I'm just wasting time inside this modern curse instead of better friends of mine...*

Anyway, it's almost May 31st, on this date, one year ago, I have pushed commit e4152c4a70ea1c3033073d8cd27b7e07c89f382c that had marked the end to the active development stage, and was the first ever milestone we've reached with the team.

## Source code, etc.
- [x] #22 is done
  - [x] #1 is fixed
  - [x] #21 is implemented
  - [x] #24 is resolved
  - [x] #26 is resolved
- [x] #4 is conducted (thanks @Survivor-2-22-22)
- [x] #23 is resolved
  - [x] JSON syntax/style is OK
  - [x] Text lines reviewed (thanks @Survivor-2-22-22)
- [x] Issues with playlist fixed thanks to Rainy Day

Primary tasks done, reviewing, testing is in progress currently.

## Meta
- [x] Reddit post
  - [x] Screenshots
  - [x] Post text
- [X] Transition/recovery
  - [X] Project name and links changed
  - [x] Old contributor lists and credits were recovered
        (apparently, this was the last opportunity to do so; all cached versions are expired now)
- [x] Project updates
  - [x] CHANGELOG must contain changes
  - [x] Release announcements must credit all contributors
  - [x] Repo detached from fork network
